language: ruby
env:
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.1.0
  - PUPPET_VERSION=4.0.0
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.7.0
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
script:
  - "bundle exec rake spec"
